apiVersion: v2
dependencies:
- name: loki-distributed
  repository: https://grafana.github.io/helm-charts
  version: 0.79.1
- name: promtail
  repository: https://grafana.github.io/helm-charts
  version: 6.16.3
- name: alloy
  repository: https://grafana.github.io/helm-charts
  version: 0.6.0
description: |
  This chart installs loki-distributed.
  Loki is a log aggregation system made by Grafana Labs, and inspired by Prometheus.
name: loki-distributed
version: "0"
